name: v5 production CI/CD #pipeline for v5 production server
'on':
  push:
    branches:
      - test #push events on branch next
jobs:        
  deploy:
    name: Deploy on remote server against v5-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODHOST }}   
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRODKEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 200m
          script: |
            cd /home/ubuntu/mevris-server || git clone -b test git@github.com:Usman7030/nestjs.git
            cd /home/ubuntu/nestjs;
            git pull origin test
            aws ecr get-login-password --region us-east-2 |sudo  docker login --username AWS --password-stdin 050521377081.dkr.ecr.us-east-2.amazonaws.com
 
            echo "success! All Done"
